pool:
  vmImage: 'ubuntu-latest'

variables:
- group: aws-secrets


stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Run Terraform Plan'
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC'
        backendServiceAWS: 'aws-terraform-svc'
        backendAWSBucketName: 'terraform-state-for-demo-vpc'
        backendAWSKey: 'tf/terraform.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC'
        environmentServiceNameAWS: 'aws-terraform-svc'