trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: IsTeardownInfrastructure
  value: false
  readonly: false
- name: IsSetupInfrastructure
  value: false
  readonly: false

stages:
- stage: InfrastructureSetup
  displayName: 'Infrastructure Setup'
  condition: eq(variables['IsSetupInfrastructure'], 'true')
  jobs:
  - job: TerraformIaC
    displayName: 'Run IaC'
    steps:
    - task: TerraformTaskV4@4
      displayName: 'Initialize Terraform'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC'
        backendAWSRegion: 'us-east-1'
        backendType: 's3'
        backendServiceAWS: 'aws-terraform-svc'
        backendAWSBucketName: 'terraform-state-for-demo-vpc'
        backendAWSKey: 'tf/terraform.tfstate'
        backendAWSDynamoDBTableName: 'terraform-locks'
    - task: TerraformTaskV4@4
      name: 'terraformPlan'
      displayName: 'Plan Terraform'
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC'
        commandOptions: '-out main.tfplan'
        environmentServiceNameAWS: 'aws-terraform-svc'
    - task: TerraformTaskV4@4
      displayName: 'Apply Terraform'
      condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'))
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC'
        commandOptions: 'main.tfplan'
        environmentServiceNameAWS: 'aws-terraform-svc'

- stage: InfrastructureTeardown
  displayName: 'Infrastructure Teardown'
  condition: eq(variables['IsTeardownInfrastructure'], 'true')
  jobs:
  - job: TerraformIaC
    displayName: 'Run IaC'
    steps:
    - task: TerraformTaskV4@4
      displayName: 'Initialize Terraform'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC'
        backendAWSRegion: 'us-east-1'
        backendType: 's3'
        backendServiceAWS: 'aws-terraform-svc'
        backendAWSBucketName: 'terraform-state-for-demo-vpc'
        backendAWSKey: 'tf/terraform.tfstate'
        backendAWSDynamoDBTableName: 'terraform-locks'
    - task: TerraformTaskV4@4
      name: 'terraformDestroy'
      displayName: 'Destroy Terraform'
      inputs:
        provider: 'aws'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC'
        environmentServiceNameAWS: 'aws-terraform-svc'

    