trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: IsSetupInfrastructure
  type: boolean
  default: false
- name: IsTeardownInfrastructure
  type: boolean
  default: false

stages:
- ${{ if eq(parameters.IsSetupInfrastructure, true) }}:
  #Stage 1 - Terraform Initialization
  - stage: Init
    displayName: "Terraform Init Stage"
    jobs:
    - job: Init
      displayName: "Terraform Init Job"
      steps:
      - task: TerraformTaskV4@4
        name: 'terraformInit'
        displayName: 'Initialize Terraform'
        inputs:
          provider: 'aws'
          command: 'init'         
          workingDirectory: '$(System.DefaultWorkingDirectory)/101-VPC_With_EC2/IaC'
          backendType: 's3'
          backendAWSRegion: 'us-east-1'
          backendServiceAWS: 'aws-terraform-svc'
          backendAWSBucketName: 'terraform-state-for-demo-vpc'
          backendAWSKey: 'tf/terraform.tfstate'
          backendAWSDynamoDBTableName: 'terraform-locks'
  #Stage 2 - Terraform Plan
  - stage: Plan
    displayName: "Terraform Plan Stage"
    jobs:
    - job: Plan
      displayName: "Terraform Plan Job"
      steps:
      - task: TerraformTaskV4@4
        name: 'terraformPlan'
        displayName: 'Plan Terraform'
        inputs:
          provider: 'aws'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/101-VPC_With_EC2/IaC'
          commandOptions: '-out main.tfplan'
          environmentServiceNameAWS: 'aws-terraform-svc'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/main.tfplan'
          artifactName: 'terraformPlan'
          publishLocation: 'pipeline'
  #Stage 3 - Terraform Apply
  - stage: Apply
    displayName: "Terraform Apply Stage"
    jobs:
    - job: Apply
      displayName: "Terraform Apply Job"
      steps:
      - task: TerraformTaskV4@4
        name: 'terraformApply'
        displayName: 'Apply Terraform'
        condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'))
        inputs:
          provider: 'aws'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/101-VPC_With_EC2/IaC'
          commandOptions: 'main.tfplan'
          environmentServiceNameAWS: 'aws-terraform-svc'


#Stage 2 - Teardown Infrasturture
- ${{ if eq(parameters.IsTeardownInfrastructure, true) }}:
  - stage: InfrastructureTeardown
    displayName: 'Infrastructure Teardown'
    jobs:
    - job: TerraformIaC
      displayName: 'Infrastructure Teardown'
      steps:

      - task: TerraformTaskV4@4
        name: 'terraformInit'
        displayName: 'Initialize Terraform'
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/101-VPC_With_EC2/IaC'
          backendType: 's3'
          backendAWSRegion: 'us-east-1'
          backendServiceAWS: 'aws-terraform-svc'
          backendAWSBucketName: 'terraform-state-for-demo-vpc'
          backendAWSKey: 'tf/terraform.tfstate'
          backendAWSDynamoDBTableName: 'terraform-locks'

      - task: TerraformTaskV4@4
        name: 'terraformPlan'
        displayName: 'Plan Terraform'
        inputs:
          provider: 'aws'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/101-VPC_With_EC2/IaC'
          commandOptions: '-out main.tfplan'
          environmentServiceNameAWS: 'aws-terraform-svc'

      - task: TerraformTaskV4@4
        name: 'terraformDestroy'
        displayName: 'Destroy Terraform'
        inputs:
          provider: 'aws'
          command: 'destroy'
          workingDirectory: '$(System.DefaultWorkingDirectory)/101-VPC_With_EC2/IaC'
          environmentServiceNameAWS: 'aws-terraform-svc'